version: '3.8'
services:
  app:
    image: node:18-alpine
    container_name: imusik-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: sh -c "npm install && npm run build && npm start"
